all: Makefile
	@$(MAKE) -f /home/chuck/git/nebula-engine/nebula/external/Galaxy/components/std/build/Makefile --no-print-directory
	@$(MAKE) -f /home/chuck/git/nebula-engine/nebula/external/Galaxy/components/log/build/Makefile --no-print-directory
	@$(MAKE) -f /home/chuck/git/nebula-engine/nebula/external/Galaxy/components/console/build/Makefile --no-print-directory
	@$(MAKE) -f /home/chuck/git/nebula-engine/nebula/components/core/build/Makefile --no-print-directory
	@$(MAKE) -f /home/chuck/git/nebula-engine/nebula/components/gfx/build/Makefile --no-print-directory
	@$(MAKE) -f /home/chuck/git/nebula-engine/nebula/components/physx/build/Makefile --no-print-directory
	@$(MAKE) -f /home/chuck/git/nebula-engine/nebula/components/python/build/Makefile --no-print-directory
	@$(MAKE) -f /home/chuck/git/nebula-engine/nebula/components/final/build/Makefile --no-print-directory
	@$(MAKE) -f /home/chuck/git/nebula-engine/nebula/apps/hf1/build/Makefile --no-print-directory
Makefile: /home/chuck/git/nebula-engine/nebula/external/config.py /home/chuck/git/nebula-engine/nebula/external/Galaxy/config.py /home/chuck/git/nebula-engine/nebula/external/Galaxy/components/config.py /home/chuck/git/nebula-engine/nebula/external/Galaxy/components/std/config.py /home/chuck/git/nebula-engine/nebula/external/Galaxy/components/log/config.py /home/chuck/git/nebula-engine/nebula/external/Galaxy/components/console/config.py /home/chuck/git/nebula-engine/nebula/components/config.py /home/chuck/git/nebula-engine/nebula/components/core/config.py /home/chuck/git/nebula-engine/nebula/components/gfx/config.py /home/chuck/git/nebula-engine/nebula/components/physx/config.py /home/chuck/git/nebula-engine/nebula/components/python/config.py /home/chuck/git/nebula-engine/nebula/components/final/config.py /home/chuck/git/nebula-engine/nebula/apps/config.py /home/chuck/git/nebula-engine/nebula/apps/hf1/config.py ../config.py
	@compiler.py ..